// Admin dashboard: list, add, revoke, reactivate and relabel devices.
//
// Who: a browser session (never a token) whose device is listed in
// ADMIN_DEVICES and is still active. Everyone else gets a 404, so the page's
// existence says nothing. What: every write goes through the admin daemon;
// auth-web never touches the keystore. The one key that passes through is the
// freshly generated one, rendered once into the firmware header for the
// keychain being provisioned.

const { render, escapeHtml } = require('../render');
const { createSessionReader } = require('../session');
const { normalizeLabel } = require('../admin');
const { wrap } = require('../async');

function firmwareHeader(id, key) {
  return [
    '#pragma once', '',
    '// Generated by xAuth provisioning -- do not edit, do not commit.',
    '// The ID and the key come from the same provisioning run and must stay',
    '// together; flashing one device\'s key with another\'s ID fails every login.', '',
    `#define DEVICE_ID  "${id}"`,
    `#define SECURE_KEY "${key}"`, '',
  ].join('\n');
}

module.exports = function adminRoutes(app, deps) {
  const { config, admin, log } = deps;
  const currentSession = createSessionReader(deps);
  const isAdmin = (deviceId) => config.adminDevices.includes(deviceId);

  if (config.adminDevices.length === 0) return;   // no /admin at all

  async function page(res, session, { status = 200, notice, error, created } = {}) {
    const devices = await admin.list();
    if (devices === null) {
      log.error('admin: daemon unreachable or malformed reply');
      return res.status(503).type('html').send(render('admin', {
        device: session.deviceId, rows: '', notice: '', created: '',
        error: '<p class="error" role="alert">The admin service is not reachable. Nothing was changed.</p>',
      }));
    }
    const activeAdmins = devices.filter((d) => d.status === 'active' && isAdmin(d.id)).length;
    const rows = devices.map((d) => {
      const you = d.id === session.deviceId;
      const lastAdmin = d.status === 'active' && isAdmin(d.id) && activeAdmins === 1;
      const action = d.status === 'active'
        ? (lastAdmin
          ? '<span class="token-meta">last admin</span>'
          : `<form method="post" action="/admin/devices/revoke" data-confirm="Revoke ${escapeHtml(d.id)}${you ? ' — your own device' : ''}? Its codes, sessions and app tokens stop working within seconds.">
              <input type="hidden" name="id" value="${escapeHtml(d.id)}">
              <button type="submit" class="button button-quiet button-small">Revoke</button>
            </form>`)
        : `<form method="post" action="/admin/devices/activate">
              <input type="hidden" name="id" value="${escapeHtml(d.id)}">
              <button type="submit" class="button button-quiet button-small">Reactivate</button>
            </form>`;
      return `
        <tr class="${d.status === 'revoked' ? 'is-revoked' : ''}">
          <td><span class="chip">${escapeHtml(d.id)}</span>${you ? ' <span class="tag">you</span>' : ''}${isAdmin(d.id) ? ' <span class="tag">admin</span>' : ''}</td>
          <td><span class="dot dot-${escapeHtml(d.status)}"></span>${escapeHtml(d.status)}</td>
          <td class="token-meta">${escapeHtml(d.created ?? '—')}</td>
          <td>
            <form method="post" action="/admin/devices/label" class="label-form">
              <input type="hidden" name="id" value="${escapeHtml(d.id)}">
              <input name="label" value="${escapeHtml(d.label)}" maxlength="64" aria-label="Label for ${escapeHtml(d.id)}">
              <button type="submit" class="button button-quiet button-small">Save</button>
            </form>
          </td>
          <td class="actions">${action}</td>
        </tr>`;
    }).join('');

    res.status(status).type('html').send(render('admin', {
      device: session.deviceId,
      rows: rows || '<tr><td colspan="5" class="token-empty">No devices yet.</td></tr>',
      notice: notice ? `<p class="notice" role="status">${escapeHtml(notice)}</p>` : '',
      error: error ? `<p class="error" role="alert">${escapeHtml(error)}</p>` : '',
      created: created ? `
      <div class="new-token" role="status">
        <p><strong>Device ${escapeHtml(created.id)}</strong> created — label “${escapeHtml(created.label)}”. The key below is shown once. Save it as <code>firmware/xAuth_ID/include/securekey.hpp</code>, flash the keychain, then delete the file.</p>
        <div class="new-token-row">
          <textarea class="token-value header-value" readonly rows="8" aria-label="Firmware header">${escapeHtml(firmwareHeader(created.id, created.key))}</textarea>
        </div>
        <div class="new-token-row"><button type="button" class="button button-small" data-copy hidden>Copy header</button></div>
        <p class="hint">Write the ID <strong>${escapeHtml(created.id)}</strong> on the keychain. To let it use this dashboard, add it to <code>ADMIN_DEVICES</code> and restart auth-web.</p>
      </div>` : '',
    }));
  }

  // Admin session, or nothing. GET without a session goes to login; a
  // non-admin session gets a 404 on every method.
  async function guard(req, res, { post = false } = {}) {
    if (post) {
      const origin = req.get('origin');
      if (!origin || origin !== config.authOrigin) {
        res.status(403).type('text').send('Forbidden');
        return null;
      }
    }
    const session = await currentSession(req);
    if (!session) {
      if (post) res.status(403).type('text').send('Forbidden');
      else res.redirect(303, '/login');
      return null;
    }
    if (!isAdmin(session.deviceId)) {
      res.status(404).type('text').send('Not found');
      return null;
    }
    return session;
  }

  app.get('/admin', wrap(async (req, res) => {
    const session = await guard(req, res);
    if (session) await page(res, session);
  }));

  app.post('/admin/devices', wrap(async (req, res) => {
    const session = await guard(req, res, { post: true });
    if (!session) return;
    const label = normalizeLabel(req.body?.label);
    if (!label) return page(res, session, { status: 400, error: 'Label: 1–64 printable characters, no quotes or backslashes.' });
    const created = await admin.add(label);
    if (!created) return page(res, session, { status: 503, error: 'The device could not be created. Nothing was changed.' });
    log.info(`admin: ${session.deviceId} created device ${created.id}`);
    await page(res, session, { created: { ...created, label } });
    created.key = '';   // nothing else holds it
  }));

  for (const [action, verb, done] of [['revoke', 'revoke', 'revoked'], ['activate', 'activate', 'reactivated']]) {
    app.post(`/admin/devices/${action}`, wrap(async (req, res) => {
      const session = await guard(req, res, { post: true });
      if (!session) return;
      const id = String(req.body?.id ?? '').toUpperCase();
      if (action === 'revoke' && isAdmin(id)) {
        const devices = await admin.list();
        const activeAdmins = (devices ?? []).filter((d) => d.status === 'active' && isAdmin(d.id)).length;
        if (activeAdmins <= 1) return page(res, session, { status: 409, error: `${id} is the last active admin device. Add another admin before revoking it.` });
      }
      const result = await admin[verb](id);
      if (result === 'ok') log.info(`admin: ${session.deviceId} ${done} ${id}`);
      await page(res, session, result === 'ok'
        ? { notice: `${id} ${done}.` }
        : { status: result === 'no' ? 404 : 503, error: result === 'no' ? `No device ${id}.` : 'The admin service failed. Nothing was changed.' });
    }));
  }

  app.post('/admin/devices/label', wrap(async (req, res) => {
    const session = await guard(req, res, { post: true });
    if (!session) return;
    const id = String(req.body?.id ?? '').toUpperCase();
    const label = normalizeLabel(req.body?.label);
    if (!label) return page(res, session, { status: 400, error: 'Label: 1–64 printable characters, no quotes or backslashes.' });
    const result = await admin.relabel(id, label);
    await page(res, session, result === 'ok'
      ? { notice: `${id} relabelled.` }
      : { status: result === 'no' ? 404 : 503, error: result === 'no' ? `No device ${id}.` : 'The admin service failed. Nothing was changed.' });
  }));
};
