#include "keygen.hpp"

#include <openssl/crypto.h>
#include <openssl/rand.h>
#include <stdexcept>
#include <vector>

std::string generate_device_id(int length) {
    static const char alphabet[] = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"; // 32 chars
    std::vector<unsigned char> buf(length);
    if (RAND_bytes(buf.data(), length) != 1) throw std::runtime_error("RAND_bytes failed");

    std::string id;
    for (unsigned char b : buf) {
        // 256 is an exact multiple of 32, so this modulo introduces no bias.
        id += alphabet[b % 32];
    }
    return id;
}

std::string generate_key() {
    const int bytes = 64;
    std::vector<unsigned char> buf(bytes);
    if (RAND_bytes(buf.data(), bytes) != 1) throw std::runtime_error("RAND_bytes failed");

    static const char hex[] = "0123456789abcdef";
    std::string key;
    key.reserve(bytes * 2);
    for (unsigned char b : buf) {
        key += hex[b >> 4];
        key += hex[b & 0x0F];
    }
    OPENSSL_cleanse(buf.data(), buf.size());
    return key;
}

bool valid_label(const std::string& s) {
    if (s.empty() || s.size() > 64) return false;
    for (unsigned char c : s) {
        if (c < 0x20 || c > 0x7E || c == '"' || c == '\\') return false;
    }
    return true;
}

std::string firmware_header(const std::string& id, const std::string& key) {
    return
        "#pragma once\n\n"
        "// Generated by xAuth provisioning -- do not edit, do not commit.\n"
        "// The ID and the key come from the same provisioning run and must stay\n"
        "// together; flashing one device's key with another's ID fails every login.\n\n"
        "#define DEVICE_ID  \"" + id + "\"\n"
        "#define SECURE_KEY \"" + key + "\"\n";
}
